DROP TABLE IF EXISTS Lavoratore;
DROP TABLE IF EXISTS Recensione;
DROP TABLE IF EXISTS Biglietto;
DROP TABLE IF EXISTS Spettacolo;
DROP TABLE IF EXISTS Film;
DROP TABLE IF EXISTS Sala;
DROP TABLE IF EXISTS Cinema;
DROP TABLE IF EXISTS Indirizzo;
DROP TABLE IF EXISTS `Cast`;
DROP TABLE IF EXISTS Persona;


